### ISSUE TITLE
Upload Stock Transaction History

### ISSUE THREAD

**Issue by jdw6359** [TeamMartinez/YOLO-Client#12]
Need to figure out how to upload a file from local storage (.txt, .csv) and send to backend to parse and create StockTransaction records.

**Comment by jdw6359** [comment]
Can someone take this item?

**Comment by vuzDylan** [comment]
I can if no one else wants it

**Comment by jdw6359** [comment]
@vuzDylan How will you be sending the file (or the contents of the file) to the backend?

**Comment by jonobrien** [comment]
[js filereader](http://www.html5rocks.com/en/tutorials/file/dndfiles/) possible for js usage?
idk how good this is, totally googled `js file upload`
calendar/stock events have to be uploaded from desktop [proj doc](http://www.se.rit.edu/~swen-344/projects/projectdescription.html) 

krutz says `individual machine`/`desktop`/`local file` in reference to either stock data or calendar events.

#17 dylan's pr
[api 14](https://github.com/TeamMartinez/YOLO-api/issues/14) related
[api 8](https://github.com/TeamMartinez/YOLO-api/issues/8) related too

I'm just verifying this is the intended feature, right?  Upload files through browser to backend to be parsed and stored/displayed again?

**Comment by jdw6359** [comment]
+1 that what you described is the intended feature
