### ISSUE TITLE
download local event file for calendar

### ISSUE THREAD

**Issue by jonobrien** [TeamMartinez/YOLO-Client#13]
User needs to download json formatted data of an event.

**Comment by jdw6359** [comment]
Almost identical. See YOLO-api to see how I handled downloading stocks -- I will do the same for calendar events:
- Client triggers download event by hitting GET @ /api/calendar_events/download
- Backend will create file, and return path to client
- Client reaches out to path to retrieve file

**Comment by jonobrien** [comment]
yeah I just figured 1 issue/req

:+1:

**Comment by jonobrien** [comment]
not actually R2
