### ISSUE TITLE
Maybe add a linter

### ISSUE THREAD

**Issue by vuzDylan** [TeamMartinez/YOLO-Client#30]
I already hate this idea...

**Comment by kocsenc** [comment]
Why hate. There is a `gulp` task we can run for `jshlint`. not sure how it would work with `jsx` fiels.

**Comment by vuzDylan** [comment]
so ive added a linter to react projects before and its not that bad you just use eslint and set the type to react or what not for jsx files

**Comment by kocsenc** [comment]
You're just scared that it's going to tell you everything you be doing like a crazy boi

**Comment by vuzDylan** [comment]
linters don't like me.

**Comment by jdw6359** [comment]
The first step in adding a linter to a project is being able to admit to yourself that you need a linter.
