### ISSUE TITLE
Change background to remove pineapples and spoons

### ISSUE THREAD

**Issue by mok4ry** [TeamMartinez/YOLO-Client#43]

**Comment by mok4ry** [comment]
Anyone opposed to this?
@vuzDylan @kocsenc

**Comment by vuzDylan** [comment]
Very

**Comment by vuzDylan** [comment]
this is literally an outrage

**Comment by jdw6359** [comment]
I honestly dont understand why we were asked to remove it

**Comment by kocsenc** [comment]
Ugh. Best background and professor noticed. Which made it special. I am heavily opposed but " the customer is always right"

**Comment by vuzDylan** [comment]
Replace it with this: http://assets-s3.usmagazine.com/uploads/assets/articles/64632-john-stamos-to-reunite-with-full-house-band-jesse-and-the-rippers-on-jimmy-fallo/1374005728_109418050_john-stamos-467.jpg

**Comment by kocsenc** [comment]
Lol

**Comment by jonobrien** [comment]
yessss
