### ISSUE TITLE
github GET issues

### ISSUE THREAD

**Issue by jonobrien** [TeamMartinez/YOLO-Client#47]
https://github.com/TeamMartinez/YOLO-api/issues/19

can be handled by client directly since the GET isn't authed at all.

**Comment by jonobrien** [comment]
not sure how to tie it all together. see #56

**Comment by jdw6359** [comment]
are you having trouble hitting my api endpoint - or is it react stuff youre stuck on

**Comment by jonobrien** [comment]
not sure how to hit the endpoint with react, @vuzDylan helped somewhat but I totally got lost at the end, plus the general js syntax is new to me too.  Also need to know what you're sending me from the api @jdw6359 so i can format the html according to what you do, after the endpoint calls are setup.

**Comment by jdw6359** [comment]
you can look at the network tab of browser tools to inspect the contents of the response

**Comment by jonobrien** [comment]
mmks, still trynta figure out this react adventure too.

**Comment by jonobrien** [comment]
yolo?
