### ISSUE TITLE
Make the client look nice

### ISSUE THREAD

**Issue by vuzDylan** [TeamMartinez/YOLO-Client#6]
How the heck does this CSS framework work?!?!

**Comment by kocsenc** [comment]
PR in #31

**Comment by vuzDylan** [comment]
PR in #32

**Comment by mok4ry** [comment]
![thumbs-up](https://cloud.githubusercontent.com/assets/1236978/13826249/e6a0f474-eb8c-11e5-89bd-f6e93148d5a9.gif)
