### ISSUE TITLE
Setup log in system

### ISSUE THREAD

**Issue by vuzDylan** [TeamMartinez/YOLO-Client#7]
Github auth

**Comment by jdw6359** [comment]
@vuzDylan auth components deployed to backend

**Comment by kocsenc** [comment]
@vuzDylan This is probably done ya?

**Comment by vuzDylan** [comment]
Nope I need a cookie that tells me when Im logged in

**Comment by vuzDylan** [comment]
thats why i gave it a blocked tag

**Comment by kocsenc** [comment]
O, wouldn't that be backend?

**Comment by vuzDylan** [comment]
I mean yes but I'm waiting on that to complete before I can finish this
